<script>
    export let product;
    export let onClose;
</script>

<div class="modal-background slide-in-fwd-center" on:click={onClose}>
    <div class="modal-content slide-in-fwd-center" on:click|stopPropagation>
        <div class="infoblock slide-in-fwd-center">
            <h2>{product.name}</h2>
            <p>Categorie: {product.category}</p>
            <p class="des">
                Descriere: <span class="descr">
                    {product.description}
                </span>
            </p>
        </div>

        {#if product.image}
            <img
                src={`/${product.image}`}
                class="imageproduct"
                alt={product.name}
            />
        {/if}
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<style>
    .descr {
        background-color: aliceblue;
        padding: 10px;
        border-radius: 10px;
    }
    .des {
        display: flex;
        flex-direction: column;
    }
    h2 {
        margin-bottom: 15px;
    }
    p {
        margin-bottom: 10px;
    }
    * {
        font-family: "Trebuchet MS", "Lucida Sans Unicode", "Lucida Grande",
            "Lucida Sans", Arial, sans-serif;
    }
    .infoblock {
        width: 500px;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: start;
    }
    .imageproduct {
        width: 50%;
        height: 50%;
    }
    .modal-background {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100vh;
        background-color: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
        overflow: hidden;
        z-index: 5;
    }
    .modal-content {
        width: 50%;
        background: white;
        max-height: 90%;
        overflow: auto;
        padding: 20px;
        border-radius: 8px;
        display: flex;
        align-items: center;
    }
    .slide-in-fwd-center {
        -webkit-animation: slide-in-fwd-center 0.4s
            cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
        animation: slide-in-fwd-center 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94)
            both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2024-1-20 2:42:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    @-webkit-keyframes slide-in-fwd-center {
        0% {
            -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }
    @keyframes slide-in-fwd-center {
        0% {
            -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateZ(0);
            transform: translateZ(0);
            opacity: 1;
        }
    }

    @media screen and (max-width: 900px) {
        .modal-content {
            flex-direction: column;
            overflow: auto;
            width: 80%;
            height: 90vh;
        }
        .infoblock {
            width: 100%;
        }
        .imageproduct {
            width: 100%;
            margin-top: 20px;
            height: auto;
        }
    }
</style>
