<script>
  import "$lib/responsiv.css";
  import Header from "$lib/Header.svelte";
  import Subheader from "../lib/Subheader.svelte";
  import News from "../lib/News.svelte";
  import Footer from "../lib/Footer.svelte";
  import Info from "../lib/Info.svelte";
  import LeftMenu from "$lib/LeftMenu.svelte";
  import { openMenu } from "$lib/index.js";
  import HomeBlock from "../lib/HomeBlock.svelte";
  $: console.log($openMenu);

  // categorii :medii de cultura,cromogene,teste pcr,echipamente de laborator,despre noi,produse,contacte,parteneri
</script>

<Subheader />
<main class="app">
  <div class="header">
    <Header />
  </div>

  <LeftMenu />
  <HomeBlock />
  <News />
</main>
<Footer />

<style>
  .app {
    width: 100%;
    display: flex;
    flex-direction: column;
  }
  .header {
    position: relative;
  }
  .slide-in-left {
    -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
      both;
    animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2024-1-20 3:10:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  @-webkit-keyframes slide-in-left {
    0% {
      -webkit-transform: translateX(-1000px);
      transform: translateX(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
      opacity: 1;
    }
  }
  @keyframes slide-in-left {
    0% {
      -webkit-transform: translateX(-1000px);
      transform: translateX(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
      opacity: 1;
    }
  }
</style>
