<script>
  import Header from "./../../lib/Header.svelte";
  import Subheader from "../../lib/Subheader.svelte";
  import Footer from "../../lib/Footer.svelte";
  import Modal from "../../lib/Modal.svelte";
  import { onMount } from "svelte";
  let products = [];
  let selectedProduct = null;

  onMount(async () => {
    const response = await fetch("/products");
    products = await response.json();
  });

  function showProductDetails(product) {
    selectedProduct = product;
  }

  function closeProductDetails() {
    selectedProduct = null;
  }
</script>

<main class="cr">
  <Subheader />
  <Header />
</main>
<span class="text">MEDIUL DE CULTURA CROMOGEN</span>
<div class="newProducts">
  {#each products as product}
    <div class="box" on:click={() => showProductDetails(product)}>
      <img class="imgprod" src={`/${product.image}`} alt="" />
      <span class="name">{product.name}</span>
    </div>
  {/each}
</div>
{#if selectedProduct}
  <Modal product={selectedProduct} onClose={closeProductDetails} />
{/if}
<Footer />

<style>
  .text {
    width: 100%;
    font-family: "Lato", sans-serif;
    display: flex;
    justify-content: center;
    font-size: 35px;
    font-weight: 600;
    text-align: center;
  }
  .imgprod {
    width: 90%;
  }
  .newProducts {
    margin-top: 100px;
    padding-inline: 150px;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
  }
  .name {
    text-align: center;
    width: 100%;
    font-family: "Lato", sans-serif;
    font-weight: 600;
    margin-top: 10px;
  }
  .box {
    width: 300px;
    text-decoration: none;
    overflow: hidden;
    box-shadow: 0px 0px 10px rgba(24, 96, 221, 0.415);
    border-radius: 20px;
    height: 350px;
    display: flex;
    flex-direction: column;
    margin: 25px;
    align-items: center;
    justify-content: center;
    transition: 0.5s linear;
    cursor: pointer;
  }
  .box:hover {
    box-shadow: 0px 0px 10px rgba(24, 221, 47, 0.415);
    transform: scale3d(1.05, 1.05, 0.5);
  }
  .slide-in-fwd-center {
    -webkit-animation: slide-in-fwd-center 0.4s
      cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: slide-in-fwd-center 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94)
      both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2024-1-20 2:42:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  @-webkit-keyframes slide-in-fwd-center {
    0% {
      -webkit-transform: translateZ(-1400px);
      transform: translateZ(-1400px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateZ(0);
      transform: translateZ(0);
      opacity: 1;
    }
  }
  @keyframes slide-in-fwd-center {
    0% {
      -webkit-transform: translateZ(-1400px);
      transform: translateZ(-1400px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateZ(0);
      transform: translateZ(0);
      opacity: 1;
    }
  }
</style>
